"""add payments table

Revision ID: 17b0edb477b0
Revises: f1e2d3c4b5a6
Create Date: 2025-11-18 14:05:36.905323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b0edb477b0'
down_revision: Union[str, None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payments',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('tg_id', sa.BigInteger(), nullable=False),
        sa.Column('payment_charge_id', sa.String(length=256), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('payment_type', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_tg_id', 'payments', ['tg_id'], unique=False)
    op.create_index('ix_payments_payment_charge_id', 'payments', ['payment_charge_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_payment_charge_id', table_name='payments')
    op.drop_index('ix_payments_tg_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
