"""add migrate

Revision ID: 4dc53a7847fe
Revises: 
Create Date: 2024-06-10 09:33:19.882019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dc53a7847fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('car_numbers', postgresql.ARRAY(sa.String(length=256)), nullable=True))
    op.add_column('users', sa.Column('track_number', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'track_number')
    op.drop_column('users', 'car_numbers')
    # ### end Alembic commands ###
