"""add tracking fields

Revision ID: a1b2c3d4e5f6
Revises: 4dc53a7847fe
Create Date: 2024-12-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '4dc53a7847fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tracking_type',
                  sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column(
        'tracking_interval', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tracking_active',
                  sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column(
        'tracking_initial_order_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tracking_initial_order_id')
    op.drop_column('users', 'tracking_active')
    op.drop_column('users', 'tracking_interval')
    op.drop_column('users', 'tracking_type')
    # ### end Alembic commands ###
