"""add call fields

Revision ID: f1e2d3c4b5a6
Revises: a1b2c3d4e5f6
Create Date: 2024-12-19 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1e2d3c4b5a6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number',
                  sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('call_queue_number',
                  sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('call_purchased',
                  sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('call_completed',
                  sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('users', sa.Column('call_telegram_payment_charge_id',
                  sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'call_telegram_payment_charge_id')
    op.drop_column('users', 'call_completed')
    op.drop_column('users', 'call_purchased')
    op.drop_column('users', 'call_queue_number')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
